import '%modules%/header/header'
import '%modules%/footer/footer'
import '%modules%/slider-prod/slider-prod'
import '%modules%/slider-partners/slider-partners'
import '%modules%/slider-benefits/slider-benefits'
